### ISSUE TITLE
"Touching sprite" block behavior with clones?

### ISSUE THREAD

**Issue by adroitwhiz** [PullJosh/scratch-js#25]
In Scratch, the "touching (sprite)" block will return true if the current sprite is touching the other sprite or any of its clones. In scratch-js, it only returns true if it's touching the original sprite.

I think a good solution would be to retain the current behavior if you pass a sprite *instance* to `touching()`, but to use Scratch's behavior if you pass the sprite's *base class*. I'd like to get your opinion on it.

**Comment by PullJosh** [comment]
This makes sense, although importing the sprite class makes writing the sb-edit export code trickier. A few other options:
1) **Allow passing an array of instances.** Could also give sprites a `.andClones()` method so you can do `if (this.touching(this.sprites.sprite2.andClones())`
2) **Add a second boolean parameter** to the touching function that determines whether or not to include clones. If set to true by default, then `this.touching(this.sprites.sprite2)` would check sprite2 and all clones, while `this.touching(this.sprites.sprite2, false)` would check only the original.
3) **Don't allow checking only the parent,** because it isn't possible in Scratch anyway.

**Comment by towerofnix** [comment]
I'm pretty strongly in favor of the first idea there! It lets you easily access a sprite and its clones together, which, thanks to treating sprites as first-class objects, is good for more complex programming concepts not easily possible in Scratch.

In order to match Scratch behavior without introducing more complex syntax, we would probably want to make `andClones` return the sprite as well as any of the clones made of it, *and* any clones of those clones themselves. (But, if you do `(a clone).andClones()`, *not* clones of the parent/original sprite, IMO, since if you wanted to do that you'd just access the original object directly (`this.sprites.whatever`).)

**Comment by PullJosh** [comment]
Actually, clones of clones aren't a thing! In order to match Scratch behavior, when you clone a clone, it actually clones the original sprite. In other words, the `.clones` array will always be empty in every instance except the original.

**Comment by nanaian** [comment]
> In order to match Scratch behavior, when you clone a clone, it actually clones the original sprite. 

Aargh, that's confusing! If I understand correctly, `myClone.clone()` secretly just does `mySprite.clone()`; surely you could always compile the _create clone of sprite v_ block to `sourceSprite.clone()` but support `myClone.clone()` anyway?

**Comment by PullJosh** [comment]
> surely you could always compile the *create clone of sprite v* block to `sourceSprite.clone()`

That's... super reasonable, actually.

**Comment by PullJosh** [comment]
> * **Allow passing an array of instances.** Could also give sprites a `.andClones()` method so you can do `if (this.touching(this.sprites.sprite2.andClones())`

`.andClones()` now exists (see #32), so we can move ahead with this.
